services:

  postgres_test:
    image: postgres:17
    container_name: postgres_test
    restart: always
    volumes:
      - postgres_test_value:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker_fast:
    build: .
    container_name: celery_worker_fast
    restart: always
    command:
      celery 
      -A core.celery_config 
      worker 
      -Q fast_tasks 
      -P gevent
      --hostname=worker.fast_$${HOSTNAME} 
      --concurrency=2
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      postgres_test:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  celery_worker_normal:
    build: .
    container_name: celery_worker_normal
    restart: always
    command:
      celery -A core.celery_config worker -Q normal_tasks 
      --hostname=worker.normal_$${HOSTNAME} -P gevent --concurrency=500
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      postgres_test:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  celery_worker_slow:
    build: .
    container_name: celery_worker_slow
    restart: always
    command:
      celery 
      -A core.celery_config 
      worker 
      -Q slow_tasks 
      -P gevent 
      --hostname=worker.slow_$${HOSTNAME} 
      --concurrency=100
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    depends_on:
      postgres_test:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  # tasks_service:
  #   image: tasks_service
  #   build: .
  #   container_name: tasks_service
  #   restart: always
  #   env_file:
      # - .env
  #   ports:
  #     - 7557
  #   depends_on:
  #     postgres_test:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_started

  # nginx:
  #   image: nginx:1.25.3
  #   container_name: nginx
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./configs:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - postgres_test
  #     - celery_worker
  #     - rabbitmq
  #     - tasks_service
  #   ports:
  #     - 80:80

volumes:
  postgres_test_value:
  rabbitmq_data:
